[package]
name = "rust-wasm-vanilla"
version = "0.1.0"
authors = ["ArakiTakaki <araki_takaki@yahoo.co.jp>"]

# crate-type = ["cdylib"]
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.48"
