[package]
name = "rust-wasm-vanilla"
version = "0.1.0"
authors = ["ArakiTakaki <araki_takaki@yahoo.co.jp>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-pack = "0.8.1"
wasm-bindgen = "0.2.48"
